### ISSUE TITLE
Exception has occurred: CLR/System.Exception

### ISSUE THREAD

**Issue by mh2538** [PacktPublishing/Practical-Microservices-with-Dapr-and-.NET#4]
I got this error while trying to run chapter03 sample :

```
An unhandled exception of type 'System.Exception' occurred in System.Private.CoreLib.dll: 'Could not resolve a service of type 'System.Text.Json.JsonSerializerOptions' for the parameter 'serializerOptions' of method 'Configure' on type 'sample.microservice.reservation.Startup'.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidOperationException : No service for type 'System.Text.Json.JsonSerializerOptions' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
```

**Comment by mistral61** [comment]
The same for me.
Adding
services.AddSingleton<JsonSerializerOptions>();
in ConfigureServices in Startup.cs the error is gone, but i'm not sure if is the best approach.
The code for the exercise works ,commenting 
Console.WriteLine($"sku: {result.GetProperty("sku")} === new quantity: {result.GetProperty("quantity")}");
because it gives error, i must debug in order to understand.
In every case, ok DAPR is still in development, but ...

**Comment by DavideBedin** [comment]
Can you verify if these changes fixes it for you? In /chapter03/sample.microservice.reservation/Startup.cs I changed the method ConfigureServices to the following:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddDaprClient();
            
            services.AddSingleton(new JsonSerializerOptions()
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                PropertyNameCaseInsensitive = true,
            });
        }
```
With this change, also launching the VS Code debug configuration ".NET Core Launch w/Dapr (reservation)" works as expected.
