### ISSUE TITLE
invoking reservation-service in debug mode does not seem to work

### ISSUE THREAD

**Issue by tomboon** [PacktPublishing/Practical-Microservices-with-Dapr-and-.NET#9]
If I start order-service and reservation-service manually via the commandline it works fine. I can POST an order and the reservation-service gets invoked.

However, if I start the order-service and reservation-service in VSCode via the debug launch configuration I notice that:

- the services do not show up in the dapr dashboard
- the services do not show up in the output of  "dapr list"
- a POST to the order-service works, but when it tries to invoke the reservation-service I always get the following exception:

_Exception thrown: 'Dapr.Client.InvocationException' in System.Private.CoreLib.dll: 'An exception occurred while invoking method: 'reserve' on app-id: 'reservation-service''
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Net.Sockets.SocketException : **No connection could be made because the target machine actively refused it.**_

- a POST straight to the reservation-service does work as expected

It seems that the services cannot invoke others when running in daprd? Is this a known issue?

**Comment by dabedin** [comment]
On "dapr list" not showing Dapr applications in debugging it is expected, see https://github.com/microsoft/vscode-dapr/issues/56 and at the bottom of https://docs.dapr.io/developing-applications/ides/vscode/.
On the "No connection could be made because the target machine actively refused it" I also experienced it but it was a local issue: not sure if it was the Windows Firewall interacting or something else. While I am not able to troubleshoot, I opened a discussion on the Dapr discord on this behaviour https://discord.com/channels/778680217417809931/778693130303832135/841926130210308096.

**Comment by dabedin** [comment]
Hi @tomboon thanks for the question: I tried in my environment and I reproduced it. Apart from the Discord discussion I found the issue https://github.com/dapr/python-sdk/issues/146 with comments on the interaction of VPNs with the discovery and service-to-service components. Once I disabled the corporate VPN I had no more issues, confirming that the issue is linked to the local system configuration.

**Comment by tomboon** [comment]
Thank you for your feedback. I will look into VPN and/or windows firewall although it may be hard to change some settings on a corporate computer.

**Comment by dabedin** [comment]
Hi @tomboon can you validate this in your environment? In the launch.json for the configuration ".NET Core Launch w/Dapr (order)" you should add DAPR_HTTP_PORT to the env variables.
```
"env": {
             "ASPNETCORE_ENVIRONMENT": "Development",
             "ASPNETCORE_URLS": "http://+:5001",
             "DAPR_HTTP_PORT": "5010"
         },
```
After I disable my VPN (really invasive) I see that how the order-service is able to connect.
Please let me know.

**Comment by tomboon** [comment]
@dabedin thank you for investigating further.
I tried this and it works!

Adding "DAPR_HTTP_PORT": "5010" seems to do the trick!
When I call order-service it can reach reservation-service, regardless of whether I'm on a VPN or not.

For the sake of completeness we should add "DAPR_HTTP_PORT": "5020" in the launch.json configuration for reservation-service too.
